#######################################################################
# file name: ../purec/Makefile
# author   : Yu Liu
# email    : <ilhanwnz@hotmail.com>
# time     : Mon 28 Jan 2019 09:45:50 PM CST
#######################################################################

PROGS = insertion_sort

all: $(PROGS)

%: %.c
	$(CC) $@.c -o $@

clean:
	rm $(PROGS) -rf
